CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    ldap_username VARCHAR(100) NOT NULL,
    department VARCHAR(100),
    role_title VARCHAR(100),
    manager_id INT,
    mac_address VARCHAR(32),
    nfc_uid VARCHAR(32),
    pay_type VARCHAR(16) NOT NULL DEFAULT 'hourly',
    hourly_rate DECIMAL(10,2),
    salary_monthly DECIMAL(10,2),
    overtime_multiplier DECIMAL(4,2) NOT NULL DEFAULT 1.25,
    tax_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    social_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    pension_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    other_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    employer_social_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    employer_pension_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    employer_other_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    payment_method VARCHAR(40),
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    UNIQUE KEY unique_ldap_username (ldap_username),
    UNIQUE KEY uniq_users_nfc_uid (nfc_uid),
    FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    start_time DATETIME NOT NULL,
    end_time DATETIME,
    source VARCHAR(16) NOT NULL DEFAULT 'manual',
    note TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX idx_sessions_user_start (user_id, start_time)
);

CREATE TABLE paychecks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    period_year INT NOT NULL,
    period_month INT NOT NULL,
    pay_date DATE NOT NULL,
    pay_type VARCHAR(16) NOT NULL,
    hourly_rate DECIMAL(10,2),
    salary_monthly DECIMAL(10,2),
    total_hours DECIMAL(10,2) NOT NULL DEFAULT 0,
    overtime_hours DECIMAL(10,2) NOT NULL DEFAULT 0,
    overtime_multiplier DECIMAL(4,2) NOT NULL DEFAULT 1.25,
    base_pay DECIMAL(12,2) NOT NULL DEFAULT 0,
    overtime_pay DECIMAL(12,2) NOT NULL DEFAULT 0,
    bonus_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    allowance_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    gross_pay DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    social_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    pension_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    other_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    social_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    pension_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    other_deduction_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_deductions DECIMAL(12,2) NOT NULL DEFAULT 0,
    net_pay DECIMAL(12,2) NOT NULL DEFAULT 0,
    employer_social_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    employer_pension_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    employer_other_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
    employer_social_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    employer_pension_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    employer_other_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    payment_method VARCHAR(40),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_paycheck_period (user_id, period_year, period_month),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
